miraj.markup
============

link:https://github.com/mobileink/miraj.markup/tree/miraj[miraj.markup]
is designed to provide fully functional Clojure programming of
link:http://www.w3.org/TR/html51/[HTML5.1] and
link:https://www.polymer-project.org/1.0/[Polymer 1.x].

* <<motivation,motivation>>
* <<summary,summary>>
** <<companions,companion libraries>>
* <<status,status>>
* <<usage,usage>>
* <<api,api>>
** <<bools,boolean attributes>>
** <<voids,void elements>>
** <<empties,empty elements>>
** <<attvals,attribute values>>
** <<annots,polymer binding annotations>>
* <<validation,validation>>
* <<xforms,transformations>>
* <<co-comp,co-compilation>>
* <<conveniences,convenience wrappers>>
* <<bugs,bugs, comments, suggestions>>
* <<license,license>>

= [[motivation]] motivation

Do we really need yet another HTML-in-Clojure library?  We already
have link:https://github.com/weavejester/hiccup[Hiccup],
link:https://hoplon.io/[Hoplon], and various template-based libraries;
why another one?

miraj.markup is the foundation layer of a more ambitious project to
re-conceptualize web programming (and indeed computation) in a manner
that integrates the traditional function-oriented programming model of
Clojure and the interaction-oriented model of computation described by
(among others) Robin Milner in
link:http://www.cambridge.org/us/catalogue/catalogue.asp?isbn=0521658691[Communicating
and Mobile Systems: The π-calculus]:

[quote]
----
[T]he π-calculus can be seen as a basic model of computation.  Every
basic model rests upon a small number of primitive notions: the
π-calculus rests upon the primitive notion of _interaction_, just as
Turing machines and register machines rest upon the notion of reading
and writing a storage medium, and just as recursive equations and the
λ-calculus rest upon mathematical functions.
----

Clojure, with core.async and support for meta-programming, is the
perfect test-bed for working out an integrated model of interaction-
and function-oriented programming, and web-programming in HTML is the
perfect test case.  The first step is to treat HTML as the "machine"
language of the BVM - "Browser Virtual Machine" - just as we can treat
Javascript as the "machine" language of the JSVM (JavaScript Virtual
Machine) that runs in the BVM.  From this perspective, every HTML tag
represents a function, and a Clojure function that generates an HTML
element in string form can be viewed as a _co-function_.  Functions
are applied to and denote _values_; co-functions exhibit (and observe)
_behaviors_.  A thorough explanation of this idea is beyond the scope
of this README; interested readers should consult Milner and anything
they can find on the web discussing co-algebras from a computational
perspective.

So the primary motivation for mirja.markup and its
<<companions,companion libraries>> is to support _co-programming_ of
HTML web applications using Clojure (co-) functions.
link:https://hoplon.io/[Hoplon] apparently also represents HTML tags
as functions, but it uses something called
link:https://github.com/hoplon/hoplon/wiki/HLisp[HLisp].  Since HLisp
is both undocumented and, apparently, not Clojure, I decided to roll
my own by piggy-backing on clojure.data.xml.

Two complementary libraries are under development.  One amounts to a
protocol layer sitting between the application and the HTTP layer; its
function is to completely shield the application from the details of
HTTP - no routes, no HTTP requests, etc.  It does this by following
the example of core.async (there are libraries that already do
something like this.)  The other provides application programming
support for first-class co-functions and co-namespaces; this makes web
(co-) programming indistinguishable for ordinary Clojure programming -
no <link> elements, for example; that sort of thing is handled
automatically.  Together these libraries provide completely
transparent support for web programming/co-programming.  That's the
idea anyway, and so far it's looking pretty good.  I hope to have them
ready to share by early January 2016 if not sooner.

= [[summary]] summary

miraj.markup is derived from
link:https://github.com/clojure/data.xml[clojure.data.xml].  It
extends `data.xml` to support HTML5, which is not XML; hence the name
change.

Like data.xml, miraj.markup has the following features:

* Parses XML documents into Clojure data structures
* Emits XML from Clojure data structures
* No additional dependencies if using 1.6
* Uses StAX internally
* lazy - should allow parsing and emitting of large XML documents

In addition, miraj.markup understands HTML5 and Polymer.  It supports
the following features:

* HTML5 <<bools,boolean attributes>>

* HTML5 <<voids,void elements>>

* HTML5 <<empties,empty elements>> are always serialized with a
  closing tag, never as self-closing tags (e.g. `(element :script
  {:src "foo.js"})` generates `<script src="foo.js"></script>`, never
  `<script src="foo.js"/>`).

* Polymer <<annots,binding annotations>> - \[[one-way]] and {{two-way}}

* Functional programming of HTML apps - element constructors are functions

* <<xforms,Transformations>> - miraj.markup functions generate Clojure data
  structures (using the same Element record used by data.xml), which
  can be manipulated just like any other Clojure data structure.
  miraj.markup comes with one predefined transform:

** `miraj.markup/optimize` pulls <script> elements out of the <head>
  element and inserts them at the bottom of the page, just before the
  closing </body> tag.

* <<co-comp,Co-compilation>> - generation of a static HTML file from miraj.markup code

* support for easy-to-write <<conveniences,convenience wrappers>>

=== [[companions]] Companion libraries

`miraj.markup` uses the same primitive constructors as `data.xml`; for
example, to construct `<div class="foo">bar</div>`, one writes
`(element :div {:class "foo"} "bar")`.

Several companion libraries provide convenience wrappers for miraj.markup:

* link:https://github.com/mobileink/miraj.html[miraj.html] - provides
  one function per HTML5 element, so you can write `(div {:class
  "foo") "bar")` instead of `(element :div {:class "foo"} "bar")`.

* A series of `polymer` libraries that provide one function for each
  element in the link:https://elements.polymer-project.org/[Polymer
  catalog].  By `require`-ing these libraries with an alias you can
  write e.g. `(paper/button)` instead of `(element :paper-button)`.
  *CAVEAT:* the polymer libraries are still under development; only the iron,
  paper, and neon libraries are suitable for use now, and may be
  buggy.

** link:https://github.com/mobileink/polymer.dom[polymer.dom] - dom-repeat, dom-if, dom-bind, dom-module

** link:https://github.com/mobileink/polymer.gold[polymer.gold] - e-commerce

** link:https://github.com/mobileink/polymer.google[polymer.google] - Google web components

** link:https://github.com/mobileink/polymer.iron[polymer.iron] - visual and non-visual utility elements

** link:https://github.com/mobileink/polymer.paper[polymer.paper] - visual elements that implement Google's Material Design

** link:https://github.com/mobileink/polymer.paper.input[polymer.paper.input] - paper input elements

** link:https://github.com/mobileink/polymer.neon[polymer.neon] - special effects, i.e. animations

** link:https://github.com/mobileink/polymer.platinum[polymer.platinum] - "Elements to turn your web page into a true webapp, with push, offline, bluetooth and more."

** link:https://github.com/mobileink/polymer.molecules[polymer.molecules] - wrapped javascript libraries.

This README file documents miraj.markup only.

= [[status]] status

miraj.markup and its companion libraries are pre-alpha, proof-of-concept
software.

miraj.markup is designed to generate HTML5, not to read/parse it.  But
since it is derived from `data.xml` it should work with XML files.
See the link:https://github.com/clojure/data.xml[clojure.data.xml]
README for XML examples.

= [[usage]] usage

*NOTE:*  This library uses the pull parser that ships with JDK 1.6.  If
you running on JDK 1.6+, you do not need any additional dependencies.
If you are using JDK 1.5, you will need to include a dependency on
StAX.  More information on this is available
link:https://github.com/clojure/data.xml/blob/jdk16-pull-parser/jdk_15_readme.txt[here].

link:http://clojars.org/miraj/markup[image:http://clojars.org/miraj/markup/latest-version.svg[]]

[source,clojure]
----
;; src/test.clj
(ns test
  (:require [miraj.markup :refer :all]))

(def doc (element :html
                  (element :head
                           (element :meta {:name "description"
                                           :content "miraj.markup test"})
                           (element :script {:src "/scripts/foo.js"}))
                  (element :body
                           (element :h1 "Hello World"))))

(println doc)
=> #miraj.markup.Element{:tag :html, :attrs {}, :content (#miraj.markup.Element{...

(println (serialize doc))
=> <!doctype html><html><head><meta name="description" content="co-compile test"><script src="/scripts/foo.js"></script></head><body><h1>Hello World</h1></body></html>

(pprint doc)
<!doctype html>
<html>
    <head>
        <meta name="description" content="co-compile test">
        <script src="/scripts/foo.js"></script>
    </head>
    <body>
        <h1>Hello World</h1>
    </body>
</html>
user>

(println (optimize :js doc))
=> #miraj.markup.Element{:tag :html, :attrs {}, :content (#miraj.markup.Element{

(pprint (optimize :js doc))
<!doctype html>
<html>
    <head>
        <meta name="description" content="co-compile test">
    </head>
    <body>
        <h1>Hello World</h1>
        <script src="/scripts/foo.js"></script>
    </body>
</html>
;; NOTE: the script element has been moved

(co-compile "resources/footest.html"
            (optimize :js doc)
            :pprint)
;; resources/footest.html:
<!doctype html>
<html>
    <head>
        <meta name="description" content="co-compile test">
    </head>
    <body>
        <h1>Hello World</h1>
        <script src="/scripts/foo.js"></script>
    </body>
</html>
----

== [[api]] API

Too soon to generate official API docs.  The
link:http://clojure.github.io/data.xml/[data.xml API Reference] should
suffice.  If you need to work with XML you should use that library
instead of `miraj.markup`.  If you need to work with XHTML or some
version of HTML < 5, you'll have to look elsewhere; `miraj.markup`
only supports HTML5.  (That may change.)

To program HTML, all you need is `miraj.markup/element`, which works
the same way `data.xml/element` works (although I notice the latter is
not included in the API Reference.)  However, `miraj.markup/element`
extends `data.xml/element` to support the following features:

=== [[bools]] HTML5 link:http://www.w3.org/TR/html51/infrastructure.html#boolean-attributes[boolean attributes]

A _boolean attribute_ is either present or absent; it is not the same
as a _boolean-valued_ attribute, which as the name suggests is one
whose value is boolean.  HTML5 says "The values 'true' and 'false' are
not allowed on boolean attributes. To represent a false value, the
attribute has to be omitted altogether."

In HTML5 markup, boolean attributes do not need an attribute value; if
a value is provided, it must be either the empty string "" or it must
match the attribute name, e.g. `foo="foo"` or `foo=foo`.

To express a boolean attribute in `miraj.markup`, use Clojure `nil` as
the attribute value.  Serialization will translate {:foo nil} to a
boolean attribute without a value assignment.  For example:

[source,clojure]
----
(element :body {:unresolved nil} ...)
; serialization:  <body unresolved>...</body>
----

=== [[voids]] HTML5 link:http://www.w3.org/TR/html51/syntax.html#void-elements[void elements]

Void elements cannot have any content; they also cannot be
"self-closing"; void elements only have a start tag.  For arcane
reasons we need not discuss here.

`miraj.markup` understands void elements; no special markup is required.

[source,clojure]
----
(serialize (element :link {:rel "stylesheet" :href "foo.css"}))
 ;=> <link rel="stylesheet" href="foo.css">
----

=== [[empties]] HTML5 empty elements

Empty elements must not be self-closing.  `miraj.markup` understands
this and does the right thing:

[source,clojure]
----
(element :script {:src "foo.js"})
; serialization: <script src="foo.js"></script>
----


=== [[attvals]] attribute values

With a few exceptions, clojure attribute values go through normal
Clojure evaluation and then are serialized as strings, just as with
`data.xml`.  You can use expressions as attribute values:

[source,clojure]
----
(serialize (element :foo {:bar (* 2 3)})) ;=> <foo bar="6"></foo>
----

Note that evaluation (reduction) occurs as in normal function
evaluation, so the what gets constructed on the `miraj.markup.Element`
is the value of the expression:

[source,clojure]
----
(element :foo {:bar (* 2 3)}) ;=> #miraj.markup.Element{:tag :foo, :attrs {:bar 6}, :content ()}
----

The exceptions are:

* nil marks a boolean attribute: `(serialize (element :foo {:bar nil})) ; => <foo bar></foo>`

* Polymer annotations  (see below, <<annotations,Polymer binding annotations>>)

** keywords mark Polymer two-way annotations

** quoted symbols mark Polymer one-way annotations (unquoted symbols are evaluated normally)

* BigInt and BigDecimal end up looking like Int and Decimal (see examples below)

You can still use these as attribute values by putting them in a string literal.

Examples drawn from the Clojure
link:http://clojure.org/cheatsheet[cheatsheet] (`serialize` omitted
for brevity):

[source,clojure]
----
(element :foo {:bar 9}) ; => <foo bar="9"></foo>
(element :foo {:bar 9N}) ; => <foo bar="9"></foo>  (BigInt)
(element :foo {:bar 1.0}) ; => <foo bar="1.0"></foo>
(element :foo {:bar 1.0M}) ; => <foo bar="1.0"></foo>  (BigDecimal)
(element :foo {:bar 1/2}) ; => <foo bar="1/2"></foo>
(element :foo {:bar 0xFF}) ; => <foo bar="255"></foo>
(element :foo {:bar 2r1011}) ;=> <foo bar="11"></foo>
(element :foo {:bar 36rCrazy}) ;=> <foo bar="21429358"></foo>  (base 36)
(element :foo {:bar -1.2e-5}) ;=> <foo bar="-1.2E-5"></foo>
(element :foo {:bar true}) ; => <foo bar="true"></foo>
(element :foo {:bar false}) ; => <foo bar="false"></foo>
(element :foo {:bar (odd? 3)}) ; => <foo bar="true"></foo>

(element :foo {:bar \x}) ;=> <foo bar="x"></foo>  (char literal)
(element :foo {:bar "\377"}) ;=> <foo bar="ÿ"></foo>  (octal string literal)
(element :foo {:bar "\ucafe"}) ;=> <foo bar="쫾"></foo> (hex unicode string literal)
;; symbols
(element :foo {:bar x}) Exception: x undefined symbol
(def x "baz")
(element :foo {:bar x}) ;=> <foo bar="baz"></foo>
(element :foo {:bar 'x}) ;=> <foo bar="[[x]]"></foo>
(element :foo {:bar (quote x)}) ;=> <foo bar="[[x]]"></foo>
;; keywords
(element :foo {:bar (keyword x)}) ;=> <foo bar="{{foo}}"></foo> (x was defined above)
(element :foo {:bar (keyword y)}) ;=> Exception: y unresolved symbol
(element :foo {:bar (keyword 'x)}) ;=> <foo bar="{{x}}"></foo>
(element :foo {:bar (keyword "x")}) ;=> <foo bar="{{x}}"></foo>
(element :foo {:bar :x}) ;=> <foo bar="{{x}}"></foo>
----

*CAVEAT:* since miraj.markup is intended for HTML5 generation,
 functionality specific to XML has not been tested, e.g. CDATA
 sections, processing instructions, etc.

=== [[annots]] Polymer link:https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#property-binding[binding annotations]

"A binding annotation consists of a property name or subproperty name
enclosed in curly brackets ({{}}) or square brackets ([[]])."  See the
Polymer
link:https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#property-binding[binding
annotations] docs for details.

To express a Polymer annotation in miraj.markup, use a symbol for
one-way binding and a keyword for two-way binding:

[source,clojure]
----
;; one-way
(element :foo {:bar 'baz})
; serialization: <foo bar="[[baz]]"></foo>
;; two-way
(element :foo {:bar :baz})
; serialization: <foo bar="{{baz}}"></foo>
----

=== [[validation]] validation

`miraj.markup` does a wee bit of validation, mostly as proof of
concept.  For example, when it sees a `rel` attribute it checks to
make sure its value is one of the allowed link types, so
e.g. `(element :link {:rel "foo"}...)` will throw an exception.

=== [[xforms]] transformations

Since `miraj.markup` produces a Clojure data structure (tree or forest
of `miraj.markup.Element` records), transformations can be applied.
The library includes one transformation primitive,
`miraj.markup/xsl-xform`, that takes an XSL stylesheet (as a string)
and an Element structure and applies the former to the latter.  For an
example stylesheet see `xsl-optimize-js` in the source code.

It also comes with one predefined transform, `optimize` that uses
`xsl-xform`.  Currently `optimize` takes one "strategy" keyword, :js,
and an Element tree.  It moves all <script> elements to the bottom of
the HTML, just before the closing </body> tag:

[source,clojure]
----
(optimize :js my-doc)
----

=== [[co-comp]] co-compilation

"Co-compilation" is a fancy way of saying "writing to a file".  What
motivates the terminology is the conceptual re-orientation mentioned
in the introduction.  If we think of an HTML file as a program text,
it's a program that we generate on one machine but interpret/execute
on another.  So the process goes roughly like this

1. write the source of the program in Clojure using miraj.markup;
2. use Clojure to compile the miraj.markup code to a JVM bytecode program
3  execute JVM bytecode program, generating a data structure of miraj.markup.Element nodes;
3. serialize that data structure to a string of HTML
4. write the string to disk
5. send the string from disk to a browser client in response to a GET request
6. interpret and execute the string on the browser

If you look at this from the right (possibly cock-eyed) angle, there
is a dualism between (Clojure) compilation on the one hand, and the
process of serializing, writing, sending, etc. HTML on the other.
Just think of HTML as a kind of machine language for the BVM -
"Browser Virtual Machine".

* Compilation

** is a function of the Clojure system

** ordinarily occurs as part of a process that occurs on the dev's local machine

** translates a program text from one (source) language (e.g. Clojure) to another
   (machine or virtual machine) language (e.g. JVM bytecode)

** saves the JVM bytecode program to a local file

** the local file will later loaded and executed by a (local) OS


* Co-compilation

** is a function of the miraj.markup system

** occurs on the local machine but as part of a process that is
   inherently interactive, involving at least two different machines

** translates a program text from Clojure (the miraj.markup code) to
   another language, HTML, which can be viewed as the bytecode
   language of the Browser Virtual Machine

** saves the "BVM bytecode" (i.e. the HTML) to a local file

** the local file will later be loaded and executed _by a remote browser_


In summary, the idea is that generating HTML from miraj.markup code
(or any other HTML DSL) is just like compiling Clojure code, with one
major difference: when you write an HTML program, you're actually
_co-programming_ - using programming on a local system to program a
remote system.

The intention is also to draw a clear contrast between the idea of
_programming_ HTML and merely ingesting and emiting _documents_, which
is characteristic of template-based approaches, XML processing, etc.
From this perspective, an HTML page is a _program_, not a _datum_.

This notion is very informal and obviously needs more work, my gut
tells me that it would be possible to give something approaching a
formal definition of dualism like programming/co-programming and
compilation/co-compilation, in a way that would actually help bring
more clarity to programming activities.  That is certainly the case
for lots of other programming-related dualisms I've seen discussed,
from mathematical formalisms like algebra/co-algebra,
recursion/co-recursion, induction/co-induction, etc. to more informal
notions like co-function, co-routine, and so forth.

(Actually, cross-compilation is probably the better term.)

=== [[conveniences]] convenience wrappers

If you have a specialized HTML vocabulary, perhaps using `class`
attribution or other techniques, it's easy to write a convenience
layer to present a friendlier API.  Wrapper functions need not map
directly to the `element` primitive constructor syntax, of course; you
can rewrite things.  For example, if your vocabulary makes heavy use
of a "foo" class attribute, you can create a `foo` function such that:

[source,clojure]
----
(myvocab/foo {:bar "baz"} ...) ;=>  <div class="foo" bar="baz">...</div>
----

See the source of the <<companions,Companion Libraries>> for examples.
Also, link:https://github.com/mobileink/miraj.html[miraj.html] uses
this technique to bring a little more order to the HTML <meta> tag,
by providing, for example, some platform attributes.  So instead of
writing:

[source,html]
----
<meta name="apple-mobile-web-app-capable" content="yes" >
<meta name="apple-mobile-web-app-status-bar-style" content="default" >
<meta name="apple-mobile-web-app-title" content="My App" >
----

you can instead write:

[source,clojure]
----
(h/apple {:mobile-web-app {:capable true
	 		   :status-bar-style :default
			   :title "My App"}})
----


== [[bugs]] Bugs, Comments, Suggestions

Open an link:https://github.com/mobileink/miraj.markup/issues[issue].

== [[license]] License

Licensed under the [Eclipse Public License](http://www.opensource.org/licenses/eclipse-1.0.php).
